"""add deletion logs

Revision ID: 4c396631918d
Revises: 7fb5dd9b3be8
Create Date: 2026-05-06 19:11:53.642302

"""

from __future__ import annotations

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c396631918d"
down_revision: str | None = "7fb5dd9b3be8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_logs",
        sa.Column("siren", sa.String(length=9), nullable=True),
        sa.Column("phone_last4", sa.String(length=4), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "reason",
            sa.Enum("USER_REQUEST", "DATA_QUALITY", "DUPLICATE", name="deletion_reason"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_by_email", sa.String(length=255), nullable=True),
        sa.Column("pipedrive_organization_id", sa.Integer(), nullable=True),
        sa.Column("pipedrive_deal_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
            name=op.f("fk_deletion_logs_deleted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_logs")),
    )
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_table("deletion_logs")
    # ### end Alembic commands ###
    # Postgres requires explicit drop of the ENUM type after the table is gone.
    sa.Enum(name="deletion_reason").drop(op.get_bind(), checkfirst=True)
