"""initial schema

Revision ID: 7fb5dd9b3be8
Revises:
Create Date: 2026-05-06 17:57:04.553233

"""

from __future__ import annotations

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fb5dd9b3be8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gen_random_uuid() is built-in on PG 13+, but we enable pgcrypto for safety.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("auth0_sub", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("picture_url", sa.String(length=512), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "SALES", name="user_role"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth0_sub", name=op.f("uq_users_auth0_sub")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "blacklist",
        sa.Column("siren", sa.String(length=9), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column(
            "reason",
            sa.Enum("OPT_OUT", "INVALID", "COMPETITOR", name="blacklist_reason"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("added_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "siren IS NOT NULL OR phone_e164 IS NOT NULL",
            name=op.f("ck_blacklist_siren_or_phone_required"),
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_blacklist_added_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blacklist")),
    )
    op.create_index(
        "ix_blacklist_phone_e164",
        "blacklist",
        ["phone_e164"],
        unique=False,
        postgresql_where="phone_e164 IS NOT NULL",
    )
    op.create_index(
        "ix_blacklist_siren",
        "blacklist",
        ["siren"],
        unique=False,
        postgresql_where="siren IS NOT NULL",
    )
    op.create_table(
        "searches",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("locations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("preset", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="search_status"),
            nullable=False,
        ),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("progress_done", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_searches_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_searches")),
    )
    op.create_index(op.f("ix_searches_owner_id"), "searches", ["owner_id"], unique=False)
    op.create_index(op.f("ix_searches_status"), "searches", ["status"], unique=False)
    op.create_table(
        "prospects",
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("phone_raw", sa.String(length=64), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("gmaps_url", sa.String(length=512), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("reviews_count", sa.Integer(), nullable=True),
        sa.Column("siren", sa.String(length=9), nullable=True),
        sa.Column("naf_code", sa.String(length=10), nullable=True),
        sa.Column("legal_name", sa.String(length=500), nullable=True),
        sa.Column("legal_form", sa.String(length=255), nullable=True),
        sa.Column("creation_date", sa.Date(), nullable=True),
        sa.Column("director_name", sa.String(length=255), nullable=True),
        sa.Column("employees_range", sa.String(length=64), nullable=True),
        sa.Column("revenue_eur", sa.Integer(), nullable=True),
        sa.Column("profit_eur", sa.Integer(), nullable=True),
        sa.Column("financials_year", sa.Integer(), nullable=True),
        sa.Column("facebook_url", sa.String(length=512), nullable=True),
        sa.Column("instagram_url", sa.String(length=512), nullable=True),
        sa.Column("linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "label",
            sa.Enum("HOT", "WARM", "COLD", "UNQUALIFIED", name="prospect_label"),
            nullable=True,
        ),
        sa.Column("raw_gmaps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_insee", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_pappers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
            name=op.f("fk_prospects_search_id_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospects")),
        sa.UniqueConstraint("place_id", name="uq_prospects_place_id"),
    )
    op.create_index(op.f("ix_prospects_city"), "prospects", ["city"], unique=False)
    op.create_index(op.f("ix_prospects_label"), "prospects", ["label"], unique=False)
    op.create_index(op.f("ix_prospects_score"), "prospects", ["score"], unique=False)
    op.create_index(op.f("ix_prospects_search_id"), "prospects", ["search_id"], unique=False)
    op.create_index(
        "uq_prospects_phone_e164_notnull",
        "prospects",
        ["phone_e164"],
        unique=True,
        postgresql_where="phone_e164 IS NOT NULL",
    )
    op.create_index(
        "uq_prospects_siren_notnull",
        "prospects",
        ["siren"],
        unique=True,
        postgresql_where="siren IS NOT NULL",
    )
    op.create_table(
        "pipedrive_mappings",
        sa.Column("prospect_id", sa.UUID(), nullable=False),
        sa.Column("pipedrive_organization_id", sa.Integer(), nullable=True),
        sa.Column("pipedrive_person_id", sa.Integer(), nullable=True),
        sa.Column("pipedrive_deal_id", sa.Integer(), nullable=True),
        sa.Column("pipedrive_note_id", sa.Integer(), nullable=True),
        sa.Column("exported_by_id", sa.UUID(), nullable=True),
        sa.Column("exported_by_email", sa.String(length=255), nullable=True),
        sa.Column("sync_payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exported_by_id"],
            ["users.id"],
            name=op.f("fk_pipedrive_mappings_exported_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_pipedrive_mappings_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipedrive_mappings")),
        sa.UniqueConstraint("prospect_id", name="uq_pipedrive_mappings_prospect_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipedrive_mappings")
    op.drop_index(
        "uq_prospects_siren_notnull", table_name="prospects", postgresql_where="siren IS NOT NULL"
    )
    op.drop_index(
        "uq_prospects_phone_e164_notnull",
        table_name="prospects",
        postgresql_where="phone_e164 IS NOT NULL",
    )
    op.drop_index(op.f("ix_prospects_search_id"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_score"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_label"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_city"), table_name="prospects")
    op.drop_table("prospects")
    op.drop_index(op.f("ix_searches_status"), table_name="searches")
    op.drop_index(op.f("ix_searches_owner_id"), table_name="searches")
    op.drop_table("searches")
    op.drop_index(
        "ix_blacklist_siren", table_name="blacklist", postgresql_where="siren IS NOT NULL"
    )
    op.drop_index(
        "ix_blacklist_phone_e164", table_name="blacklist", postgresql_where="phone_e164 IS NOT NULL"
    )
    op.drop_table("blacklist")
    op.drop_table("users")
    # ### end Alembic commands ###
    # Enum types must be dropped explicitly on Postgres.
    sa.Enum(name="prospect_label").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="search_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="blacklist_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
